/*
 * Brainrex API
 * Provides anomaly detection and natural language processing technlogies to blockchain developers.
 *
 * OpenAPI spec version: 1.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Brainrex) {
      root.Brainrex = {};
    }
    root.Brainrex.ExchangeAssetsResponseInner = factory(root.Brainrex.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The ExchangeAssetsResponseInner model module.
   * @module model/ExchangeAssetsResponseInner
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ExchangeAssetsResponseInner</code>.
   * @alias module:model/ExchangeAssetsResponseInner
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ExchangeAssetsResponseInner</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExchangeAssetsResponseInner} obj Optional instance to populate.
   * @return {module:model/ExchangeAssetsResponseInner} The populated <code>ExchangeAssetsResponseInner</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('tradinSym'))
        obj.tradinSym = ApiClient.convertToType(data['tradinSym'], 'String');
      if (data.hasOwnProperty('symbol'))
        obj.symbol = ApiClient.convertToType(data['symbol'], 'String');
    }
    return obj;
  }

  /**
   * Highest price of the time frame with two decimal points
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * Percetange change in the last 24 hours
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * Volume of currency exchanged in the time frame with two decimal points
   * @member {String} tradinSym
   */
  exports.prototype.tradinSym = undefined;

  /**
   * Volume of currency exchanged in the time frame with two decimal points
   * @member {String} symbol
   */
  exports.prototype.symbol = undefined;

  return exports;

}));
