/*
 * BrainRex API
 * The Brainrex API is a collection of analytics tools and data integrations made for blockchain developers. In particular we offer Natural Language Processing and Anomaly detection algorithms that have been fine tune to understand text data and time series in the domain speficic setting of cryptocurrency and blockchain technology. This technology is intended to be use as building blocks to bigger applications, we offer examples on how to use them for Trading Backtesting and Smart Contract anomaly monitoring.
 *
 * OpenAPI spec version: 1.0.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The OrderbookRequest model module.
 * @module model/OrderbookRequest
 * @version 1.0.2
 */
export class OrderbookRequest {
  /**
   * Constructs a new <code>OrderbookRequest</code>.
   * @alias module:model/OrderbookRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OrderbookRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderbookRequest} obj Optional instance to populate.
   * @return {module:model/OrderbookRequest} The populated <code>OrderbookRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OrderbookRequest();
      if (data.hasOwnProperty('base_trading_symbol'))
        obj.baseTradingSymbol = ApiClient.convertToType(data['base_trading_symbol'], 'String');
      if (data.hasOwnProperty('exchange'))
        obj.exchange = ApiClient.convertToType(data['exchange'], 'String');
      if (data.hasOwnProperty('limit'))
        obj.limit = ApiClient.convertToType(data['limit'], 'Number');
      if (data.hasOwnProperty('quote_trading_symbol'))
        obj.quoteTradingSymbol = ApiClient.convertToType(data['quote_trading_symbol'], 'String');
    }
    return obj;
  }
}

/**
 * Name of the currency pair
 * @member {String} baseTradingSymbol
 */
OrderbookRequest.prototype.baseTradingSymbol = undefined;

/**
 * Name of the exchange
 * @member {String} exchange
 */
OrderbookRequest.prototype.exchange = undefined;

/**
 * Limit depth to extract from the orderbook
 * @member {Number} limit
 */
OrderbookRequest.prototype.limit = undefined;

/**
 * Name of the data format availables (standard)
 * @member {String} quoteTradingSymbol
 */
OrderbookRequest.prototype.quoteTradingSymbol = undefined;

