/*
 * Brainrex API
 * Provides anomaly detection and natural language processing technlogies to blockchain developers.
 *
 * OpenAPI spec version: 1.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Brainrex) {
      root.Brainrex = {};
    }
    root.Brainrex.Text = factory(root.Brainrex.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Text model module.
   * @module model/Text
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Text</code>.
   * The text object takes any string of text.
   * @alias module:model/Text
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Text</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Text} obj Optional instance to populate.
   * @return {module:model/Text} The populated <code>Text</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('text'))
        obj.text = ApiClient.convertToType(data['text'], 'String');
    }
    return obj;
  }

  /**
   * String of text or document to be analyzed
   * @member {String} text
   */
  exports.prototype.text = undefined;

  return exports;

}));
