/*
 * Brainrex API
 * Provides anomaly detection and natural language processing technlogies to blockchain developers.
 *
 * OpenAPI spec version: 1.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Brainrex);
  }
}(this, function(expect, Brainrex) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('OrderbookRequest', function() {
      beforeEach(function() {
        instance = new Brainrex.OrderbookRequest();
      });

      it('should create an instance of OrderbookRequest', function() {
        // TODO: update the code to test OrderbookRequest
        expect(instance).to.be.a(Brainrex.OrderbookRequest);
      });

      it('should have the property baseTradingSymbol (base name: "base_trading_symbol")', function() {
        // TODO: update the code to test the property baseTradingSymbol
        expect(instance).to.have.property('baseTradingSymbol');
        // expect(instance.baseTradingSymbol).to.be(expectedValueLiteral);
      });

      it('should have the property exchange (base name: "exchange")', function() {
        // TODO: update the code to test the property exchange
        expect(instance).to.have.property('exchange');
        // expect(instance.exchange).to.be(expectedValueLiteral);
      });

      it('should have the property limit (base name: "limit")', function() {
        // TODO: update the code to test the property limit
        expect(instance).to.have.property('limit');
        // expect(instance.limit).to.be(expectedValueLiteral);
      });

      it('should have the property quoteTradingSymbol (base name: "quote_trading_symbol")', function() {
        // TODO: update the code to test the property quoteTradingSymbol
        expect(instance).to.have.property('quoteTradingSymbol');
        // expect(instance.quoteTradingSymbol).to.be(expectedValueLiteral);
      });

    });
  });

}));
