/*
 * Brainrex API
 * Provides anomaly detection and natural language processing technlogies to blockchain developers.
 *
 * OpenAPI spec version: 1.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Brainrex);
  }
}(this, function(expect, Brainrex) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SupportedExchanges', function() {
      beforeEach(function() {
        instance = new Brainrex.SupportedExchanges();
      });

      it('should create an instance of SupportedExchanges', function() {
        // TODO: update the code to test SupportedExchanges
        expect(instance).to.be.a(Brainrex.SupportedExchanges);
      });

      it('should have the property bestCaseFee (base name: "bestCaseFee")', function() {
        // TODO: update the code to test the property bestCaseFee
        expect(instance).to.have.property('bestCaseFee');
        // expect(instance.bestCaseFee).to.be(expectedValueLiteral);
      });

      it('should have the property worstCaseFee (base name: "worstCaseFee")', function() {
        // TODO: update the code to test the property worstCaseFee
        expect(instance).to.have.property('worstCaseFee');
        // expect(instance.worstCaseFee).to.be(expectedValueLiteral);
      });

      it('should have the property exchange (base name: "exchange")', function() {
        // TODO: update the code to test the property exchange
        expect(instance).to.have.property('exchange');
        // expect(instance.exchange).to.be(expectedValueLiteral);
      });

    });
  });

}));
