/*
 * Brainrex API
 * Provides anomaly detection and natural language processing technlogies to blockchain developers.
 *
 * OpenAPI spec version: 1.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Brainrex);
  }
}(this, function(expect, Brainrex) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('TickerResponseInner', function() {
      beforeEach(function() {
        instance = new Brainrex.TickerResponseInner();
      });

      it('should create an instance of TickerResponseInner', function() {
        // TODO: update the code to test TickerResponseInner
        expect(instance).to.be.a(Brainrex.TickerResponseInner);
      });

      it('should have the property lastUpdated (base name: "lastUpdated")', function() {
        // TODO: update the code to test the property lastUpdated
        expect(instance).to.have.property('lastUpdated');
        // expect(instance.lastUpdated).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property percentChange24hUsd (base name: "percentChange24hUsd")', function() {
        // TODO: update the code to test the property percentChange24hUsd
        expect(instance).to.have.property('percentChange24hUsd');
        // expect(instance.percentChange24hUsd).to.be(expectedValueLiteral);
      });

      it('should have the property priceBtc (base name: "priceBtc")', function() {
        // TODO: update the code to test the property priceBtc
        expect(instance).to.have.property('priceBtc');
        // expect(instance.priceBtc).to.be(expectedValueLiteral);
      });

      it('should have the property priceUsd (base name: "priceUsd")', function() {
        // TODO: update the code to test the property priceUsd
        expect(instance).to.have.property('priceUsd');
        // expect(instance.priceUsd).to.be(expectedValueLiteral);
      });

      it('should have the property symbol (base name: "symbol")', function() {
        // TODO: update the code to test the property symbol
        expect(instance).to.have.property('symbol');
        // expect(instance.symbol).to.be(expectedValueLiteral);
      });

    });
  });

}));
